# Generated by Django 3.0.2 on 2020-01-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Link to _squared_ image for user avatar', null=True),
        ),
    ]
