# Generated by Django 3.0.2 on 2020-01-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0002_siteuser_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='avatar_url',
        ),
    ]
