# Generated by Django 2.2.16 on 2020-10-07 16:12

from django.db import migrations, models
import django.db.models.deletion
import djangoapps.lms_cms.models.lmscms_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsConfigCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='lms_cms_commentsconfigcmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('attach_to', models.CharField(choices=[('Course', 'Attach to course'), ('Flow', 'Attach to flow')], default='Flow', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CourseLessonsConfigCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='lms_cms_courselessonsconfigcmsplugin', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HtmlCMSPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='lms_cms_htmlcmspluginconfig', serialize=False, to='cms.CMSPlugin')),
                ('content', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='LessonNavigationCMSPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='lms_cms_lessonnavigationcmspluginconfig', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PageRowColumnConfigCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='lms_cms_pagerowcolumnconfigcmsplugin', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='VideoYoutubeConfigCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='lms_cms_videoyoutubeconfigcmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('youtube_id', models.CharField(default='', max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FlowParticipants',
            fields=[
            ],
            options={
                'verbose_name': 'Participants',
                'verbose_name_plural': 'Participnts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lms.flow',),
        ),
        migrations.CreateModel(
            name='FlowSchedule',
            fields=[
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lms.flow',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', verbose_name='Your answer')),
                ('file', models.FileField(blank=True, null=True, upload_to=djangoapps.lms_cms.models.lmscms_models.participant_directory)),
                ('hide_from_others', models.BooleanField(default=False, verbose_name='Hide from others')),
                ('check_result', models.CharField(blank=True, choices=[(None, 'Just comment'), ('accepted', 'Accepted'), ('failed', 'Failed'), ('rejected', 'Rejected')], max_length=30, null=True, verbose_name='Check result')),
                ('score', models.IntegerField(blank=True, default=None, help_text='Score for student response', null=True, verbose_name='Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_lesson', models.ForeignKey(help_text='Discussion attached to the Course Lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='lms.CourseLesson')),
                ('flow_lesson', models.ForeignKey(help_text='Discussion attached to Flow Lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='lms.FlowLesson')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lms_cms.Comment')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.Participant')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
    ]
