# Generated by Django 2.2.16 on 2020-09-30 21:44

from django.db import migrations

STUDENTS_GROUP_NAME = 'Students'
TEACHERS_GROUP_NAME = 'Teachers'
ADMINS_GROUP_NAME = 'Curators'


def create_groups(apps, schema_editor):
    # version than this migration expects. We use the historical version.
    Group = apps.get_model('auth', 'Group')
    for group_name in STUDENTS_GROUP_NAME, TEACHERS_GROUP_NAME, ADMINS_GROUP_NAME:
        if not Group.objects.filter(name=group_name).exists():
            Group.objects.create(name=group_name)


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
