# Generated by Django 2.2.16 on 2020-10-11 22:31

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('lms', '0002_auto_20201012_0131'),
        ('lms_cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsLesson',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lms.Lesson')),
                ('show_common_content', models.BooleanField(default=True, help_text='Display content common for all lessons across course at the bottom of lesson content')),
                ('lesson_content', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_content', slotname='lesson_content', to='cms.Placeholder')),
                ('support_content', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_content', slotname='support_content', to='cms.Placeholder')),
            ],
            options={
                'abstract': False,
            },
            bases=('lms.lesson',),
        ),
        migrations.CreateModel(
            name='CmsCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lms.Course')),
                ('icon', models.CharField(default='fas fa-graduation-cap', max_length=100)),
                ('common_content', cms.models.fields.PlaceholderField(editable=False, help_text='Content shown in each course lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_common_content', slotname='lesson_common_content', to='cms.Placeholder')),
                ('flow_content', cms.models.fields.PlaceholderField(editable=False, help_text='Content shown on the flow index page', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_content', slotname='flow_content', to='cms.Placeholder')),
            ],
            options={
                'abstract': False,
            },
            bases=('lms.course',),
        ),
    ]
