# Generated by Django 2.2.16 on 2020-10-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cms', '0002_cmscourse_cmslesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmscourse',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='cmslesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
    ]
