# Generated by Django 2.2.16 on 2020-10-04 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_auto_20201004_2254'),
        ('lms_cms', '0002_auto_20201001_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lesson',
        ),
        migrations.AddField(
            model_name='comment',
            name='course_lesson',
            field=models.ForeignKey(help_text='Discussion attached to the Course Lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='lms.Lesson'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='flow_lesson',
            field=models.ForeignKey(help_text='Discussion attached to Flow Lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='lms.FlowLesson'),
        ),
        migrations.AlterField(
            model_name='commentsconfigcmsplugin',
            name='attach_to',
            field=models.CharField(choices=[('Course', 'Attach to course'), ('Flow', 'Attach to flow')], default='Flow', max_length=20),
        ),
    ]
