# Generated by Django 2.2.16 on 2020-10-05 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cms', '0003_auto_20201004_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='course_lesson',
            field=models.ForeignKey(help_text='Discussion attached to the Course Lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='lms.CourseLesson'),
        ),
    ]
