# Generated by Django 2.2.16 on 2020-10-01 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='flowlesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['code'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.RemoveField(
            model_name='flow',
            name='group',
        ),
        migrations.RemoveField(
            model_name='flowlesson',
            name='number',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_stop_lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='number',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='course',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='number',
        ),
        migrations.AddField(
            model_name='course',
            name='flow_has_individual_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='lessons',
            field=models.ManyToManyField(related_name='in_units', to='lms.Lesson'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='StudyRouteUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('study_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.StudyRoute')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.Unit')),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
        migrations.AddField(
            model_name='studyroute',
            name='units',
            field=models.ManyToManyField(through='lms.StudyRouteUnit', to='lms.Unit'),
        ),
        migrations.AddField(
            model_name='course',
            name='study_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.StudyRoute'),
        ),
        migrations.AddField(
            model_name='flow',
            name='study_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.StudyRoute'),
        ),
    ]
