# Generated by Django 3.0.2 on 2020-01-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPerson',
        ),
    ]
