# Generated by Django 3.0.2 on 2020-01-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_delete_userperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
