# Generated by Django 3.0.2 on 2020-01-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20200106_1530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('learning', 'unit')},
        ),
    ]
