# Generated by Django 2.2.16 on 2020-10-17 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20201012_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_objective',
            field=models.TextField(default='', help_text='Что студент научится делать, поймет в результате прохождения курса', max_length=4000),
        ),
        migrations.AlterField(
            model_name='participantlesson',
            name='check_result',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('failed', 'Failed'), ('rejected', 'Rejected')], default=None, help_text='Check result for last response', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='participantlesson',
            name='score',
            field=models.IntegerField(blank=True, default=None, help_text='Score for last teacher response', null=True, verbose_name='Score'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('answers_json', models.TextField(help_text='JSON answers of the student on questions of the lesson', max_length=2000)),
                ('when_sent_by_student', models.DateTimeField(blank=True, help_text='When the student send this response', null=True)),
                ('when_checked_by_teacher', models.DateTimeField(blank=True, help_text='When the teacher check this response', null=True)),
                ('comments_json', models.TextField(help_text="JSON comments on student's answers. Structure: question_code: answer text", max_length=10000)),
                ('check_comment', models.TextField(blank=True, help_text='Comment on this whole response. Structure: question_code: {"score": value, "comment": value}', null=True)),
                ('is_accepted', models.BooleanField(blank=True, help_text="Is student's response accepted", null=True)),
                ('score', models.IntegerField(blank=True, help_text='Overall score for this response', null=True)),
                ('assigned_to', models.ForeignKey(help_text='The teacher who is to check this response', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lms.Participant')),
                ('participant_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='lms.ParticipantLesson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('code', models.SlugField(help_text='Код вопроса. Уникален среди вопросов этого урока', max_length=100)),
                ('name', models.CharField(help_text='Вопрос', max_length=200)),
                ('text', models.TextField(blank=True, help_text='Текст вопроса', max_length=3000, null=True)),
                ('type', models.CharField(blank=True, choices=[('CHAR_FIELD', 'Строка'), ('TEXT_FIELD', 'Текст'), ('INTEGER_FIELD', 'Целое число'), ('SELECT_FIELD', 'Выбор одного из списка'), ('MULTISELECT_FIELD', 'Выбор нескольких из списка'), ('RADIO_FIELD', 'Радио кнопки'), ('CHECKBOXES_FIELD', 'Чекбоксы'), ('URL_FIELD', 'URL'), ('EMAIL_FIELD', 'Email'), ('FILE_FIELD', 'Файл')], max_length=100, null=True, verbose_name='Тип')),
                ('choices', models.TextField(help_text='Возможные значения (если применимо)', max_length=1000)),
                ('required', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, help_text='Оценка за правильный ответ на вопрос', null=True, verbose_name='Оценка')),
                ('is_autocheck', models.BooleanField(default=False, help_text='Если "Да", то должно быть заполнено поле "Правильный ответ"', verbose_name='Авто проверка?')),
                ('correct_answer', models.TextField(blank=True, help_text='Значение правильного ответа. В нескольких значений - каждое значение на отдельной строке', max_length=20000, null=True, verbose_name='Правильный ответ')),
                ('lesson', models.ForeignKey(help_text='Урок к которому относится', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.Lesson')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
