# Generated by Django 2.2.16 on 2020-10-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20201018_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='flow',
            options={'verbose_name': 'Поток', 'verbose_name_plural': 'Потоки'},
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_objective',
            field=models.TextField(default='', help_text='Что студент научится делать в результате прохождения курса', max_length=4000),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
        ),
    ]
