# Generated by Django 2.2.16 on 2020-10-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_unit_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.RemoveField(
            model_name='studyrouteunit',
            name='study_route',
        ),
        migrations.RemoveField(
            model_name='studyrouteunit',
            name='unit',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='flow_has_individual_route',
        ),
        migrations.RemoveField(
            model_name='course',
            name='study_route',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='study_route',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='lessons',
        ),
        migrations.AddField(
            model_name='flowlesson',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lms.Unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='lms.Course'),
        ),
        migrations.DeleteModel(
            name='StudyRoute',
        ),
        migrations.DeleteModel(
            name='StudyRouteUnit',
        ),
        migrations.AddField(
            model_name='courselesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='lms.Course'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lms.Lesson'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='lms.Unit'),
        ),
    ]
