# Generated by Django 2.2.16 on 2020-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20201002_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowlesson',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='flowlesson',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
