# Generated by Django 2.2.16 on 2020-10-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20201018_0120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='LessonResponse',
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_objective',
            field=models.TextField(blank=True, default='', help_text='Что студент научится делать в результате прохождения курса', max_length=4000, verbose_name='Цель обучения'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='#'),
        ),
        migrations.AlterField(
            model_name='flowlesson',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='#'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='brief',
            field=models.TextField(blank=True, help_text='Описание содержимого урока', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='Возможные значения (если применимо)', max_length=1000, null=True, verbose_name='Варианты ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.SlugField(help_text='Уникален среди вопросов этого урока', max_length=100, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Значение правильного ответа. В нескольких значений - каждое значение на отдельной строке', max_length=20000, null=True, verbose_name='Правильный ответ(ы)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='#'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('String', 'Строка'), ('Integer', 'Целое число')], max_length=100, null=True, verbose_name='Тип ответа'),
        ),
    ]
