# Generated by Django 3.0.2 on 2020-01-23 03:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20200108_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('text/plain', 'Text'), ('text/html', 'Html'), ('text/markdown', 'Markdown'), ('link/uri', 'Link'), ('video/youtube', 'Video')], default='text/html', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.SlugField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.SlugField(help_text='Short code to easily identify this unit across the Course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='order',
            field=models.IntegerField(help_text='Ordering number among the course'),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('course', 'code')},
        ),
        migrations.CreateModel(
            name='UnitContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Content')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Unit')),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='order',
        ),
        migrations.RemoveField(
            model_name='content',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='section',
            name='code',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='slug',
        ),
        migrations.AddField(
            model_name='unit',
            name='contents',
            field=models.ManyToManyField(through='lms.UnitContent', to='lms.Content'),
        ),
    ]
