# Generated by Django 3.0.2 on 2020-01-06 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20200106_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='contents',
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lms.Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('unit', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('unit', 'order')},
        ),
    ]
