# Generated by Django 3.0.2 on 2020-01-23 04:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20200123_0602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['course', 'order', 'code']},
        ),
        migrations.AlterModelOptions(
            name='unitcontent',
            options={'ordering': ['order', 'unit', 'content']},
        ),
        migrations.AlterField(
            model_name='learning',
            name='code',
            field=models.SlugField(default=uuid.uuid4, max_length=100),
        ),
    ]
