# Generated by Django 2.2.16 on 2020-10-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20201018_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresponse',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The teacher who is to check this response', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lms.Participant'),
        ),
    ]
