# Generated by Django 2.2.16 on 2020-10-21 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_auto_20201018_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default=uuid.uuid4, max_length=200, unique=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название вебинара')),
                ('state', models.CharField(default='DRAFT', max_length=100, verbose_name='Состояние')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало в')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Продолжительность ЧЧ:ММ')),
                ('platform', models.CharField(blank=True, max_length=100, null=True, verbose_name='Платформа вебинаров')),
                ('platform_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='timing_type',
            field=models.CharField(choices=[('ON_DEMAND', 'в удобное время'), ('ONLINE', 'в определенное время')], default='ON_DEMAND', help_text='В какое время участник может получить доступ к материалам урока. Доступ к вебинарам может быть только в определенное время.', max_length=100, verbose_name='Вид доступа'),
        ),
    ]
