# Generated by Django 3.0.2 on 2020-01-23 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_auto_20200123_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='code',
            field=models.SlugField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
