# Generated by Django 2.2.16 on 2020-10-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_auto_20201003_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
    ]
