# Generated by Django 2.2.16 on 2020-10-21 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20201021_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowlesson',
            name='webinar',
            field=models.ForeignKey(blank=True, help_text='Вебинар этого урока', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.Webinar', verbose_name='Вебинар'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.Webinar'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='timing_type',
            field=models.CharField(choices=[('ON_DEMAND', 'в удобное время'), ('ONLINE', 'в определенное время')], default='ON_DEMAND', help_text='В какое время участник может получить доступ к материалам урока. Попасть на вебинар может быть только в определенное время.', max_length=100, verbose_name='Вид доступа'),
        ),
    ]
