# Generated by Django 3.0.2 on 2020-01-23 05:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20200123_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.SlugField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
