# Generated by Django 2.2.16 on 2020-10-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20201003_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='lms.Unit'),
        ),
    ]
