# Generated by Django 2.2.16 on 2020-10-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_auto_20201003_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(default='fas fa-graduation-cap', max_length=100),
        ),
    ]
