# Generated by Django 2.2.16 on 2020-10-21 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_auto_20201021_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowlesson',
            name='webinar',
        ),
        migrations.AddField(
            model_name='flowlesson',
            name='lesson_webinar',
            field=models.ForeignKey(blank=True, help_text='Вебинар урока для данного потока. Если не указан, то используется вебинар урока.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.Webinar', verbose_name='Вебинар'),
        ),
    ]
