# Generated by Django 3.0.2 on 2020-01-23 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_auto_20200123_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='code',
            field=models.SlugField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.SlugField(default=uuid.uuid4, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.SlugField(default=uuid.uuid4, help_text='Short code to easily identify this unit across the Course'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'code')},
        ),
    ]
