# Generated by Django 2.2.16 on 2020-10-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_auto_20201021_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowlesson',
            old_name='lesson_webinar',
            new_name='flow_webinar',
        ),
    ]
