# Generated by Django 2.2.16 on 2020-10-04 07:09

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('lms', '0009_course_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='flow_content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='flow_content', to='cms.Placeholder'),
        ),
    ]
