# Generated by Django 2.2.16 on 2020-10-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_course_flow_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opened', models.BooleanField(default=False)),
                ('when_completed', models.DateTimeField(blank=True, help_text='When the student has marked lesson as completed', null=True)),
                ('when_checked', models.DateTimeField(blank=True, help_text='When the teacher has checked the task', null=True)),
                ('check_result', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('failed', 'Failed'), ('rejected', 'Rejected')], default=None, max_length=30, null=True, verbose_name='Check result')),
                ('score', models.IntegerField(blank=True, default=None, help_text='Score for student response', null=True, verbose_name='Score')),
                ('flow_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lms.FlowLesson')),
            ],
            options={
                'ordering': ['student', 'flow_lesson'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.AddField(
            model_name='studentlesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to='lms.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentlesson',
            unique_together={('student', 'flow_lesson')},
        ),
    ]
