# Generated by Django 2.2.16 on 2020-10-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_auto_20201004_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlesson',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lms.Lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlesson',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Ordering number'),
        ),
        migrations.AddField(
            model_name='studentlesson',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lms.Unit'),
        ),
        migrations.AddField(
            model_name='studentlesson',
            name='when_opened',
            field=models.DateTimeField(blank=True, help_text='When the lesson becomes accessible for sudent', null=True),
        ),
        migrations.AlterField(
            model_name='flowlesson',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Ordering number'),
        ),
        migrations.AlterField(
            model_name='studentlesson',
            name='flow_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lms.FlowLesson'),
        ),
    ]
