# Generated by Django 2.2.16 on 2020-10-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_auto_20201004_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='support_content',
        ),
    ]
