# Generated by Django 2.2.16 on 2020-10-04 14:18

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_remove_lesson_support_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='lesson_content', to='cms.Placeholder'),
        ),
    ]
