# Generated by Django 2.2.16 on 2020-10-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_auto_20201004_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowlesson',
            name='course_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lms.CourseLesson'),
        ),
    ]
