# Generated by Django 2.2.16 on 2020-10-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_flowlesson_course_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='content',
            new_name='lesson_content',
        ),
    ]
