# Generated by Django 2.2.16 on 2020-10-04 14:59

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('lms', '0018_auto_20201004_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='support_content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_content', slotname='support_content', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_content', slotname='lesson_content', to='cms.Placeholder'),
        ),
    ]
