# Generated by Django 2.2.16 on 2020-10-04 15:02

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('lms', '0019_auto_20201004_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_static',
            field=cms.models.fields.PlaceholderField(editable=False, help_text='Content shown in each course lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_static', slotname='lesson-static', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='course',
            name='flow_content',
            field=cms.models.fields.PlaceholderField(editable=False, help_text='Content shown on the flow index page', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_content', slotname='flow_content', to='cms.Placeholder'),
        ),
    ]
