# Generated by Django 2.2.16 on 2020-10-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_auto_20201004_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlesson',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='studentlesson',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='studentlesson',
            name='unit',
        ),
    ]
