# Generated by Django 2.2.16 on 2020-10-05 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_auto_20201005_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantlesson',
            options={'ordering': ['participant', 'flow_lesson']},
        ),
        migrations.AddField(
            model_name='participantlesson',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participant_lessons', to='lms.Participant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='participantlesson',
            unique_together={('participant', 'flow_lesson')},
        ),
        migrations.RemoveField(
            model_name='participantlesson',
            name='student',
        ),
    ]
