# Generated by Django 3.0.1 on 2019-12-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseflow',
            name='content_repository_branch_name',
        ),
        migrations.RemoveField(
            model_name='courseflow',
            name='status',
        ),
        migrations.AddField(
            model_name='courseflow',
            name='state',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseflow',
            name='code',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
