# Generated by Django 2.2.3 on 2019-07-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20190730_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.AddField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(to='study.Author'),
        ),
        migrations.AddField(
            model_name='course',
            name='long_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
