# Generated by Django 2.2.16 on 2020-10-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProduct',
            fields=[
                ('digitalproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp.DigitalProduct')),
                ('short_description', models.CharField(blank=True, max_length=250, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Easy'), (3, 'Medium'), (4, 'Expert')], null=True)),
                ('number_of_lessons', models.IntegerField(blank=True, null=True)),
                ('number_of_tasks', models.IntegerField(blank=True, null=True)),
                ('number_of_video_materials', models.IntegerField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Например "3 мес 2 недели"', null=True)),
                ('goals', models.TextField(blank=True, help_text='Что студент будет уметь после окончании курса', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('erp.digitalproduct',),
        ),
    ]
