# Generated by Django 3.1.1 on 2020-09-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientorder',
            old_name='document_uuid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='document_uuid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='paymentin',
            old_name='document_uuid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='document_uuid',
            new_name='uuid',
        ),
    ]
