# Generated by Django 3.0.2 on 2020-01-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='paymentin',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='paymentin',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='items',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='shipmentitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shipmentitem',
            name='shipment',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='PaymentIn',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='ShipmentItem',
        ),
    ]
