# Generated by Django 2.2.16 on 2020-09-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseproduct',
            name='items',
            field=models.ManyToManyField(to='lms.Course'),
        ),
    ]
