# Generated by Django 3.1.1 on 2020-09-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseproduct',
            name='on_invoice_payed',
            field=models.CharField(blank=True, choices=[['ENROLL', 'Enroll student']], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseproduct',
            name='on_order_new',
            field=models.CharField(blank=True, choices=[['ENROLL', 'Enroll student']], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='state',
            field=models.CharField(choices=[('NEW', 'Новый'), ('WAITING', 'Ожидает'), ('COMPLETED', 'Выполнен'), ('PROCESSING', 'Исполняется'), ('CANCELLED', 'Отменён')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseproduct',
            name='goals',
            field=models.TextField(blank=True, help_text='Что студент будет уметь после прохождения курса', null=True),
        ),
        migrations.AlterField(
            model_name='courseproduct',
            name='number_of_lessons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseproduct',
            name='number_of_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseproduct',
            name='number_of_video_materials',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.CharField(choices=[('NEW', 'Новый'), ('WAITING', 'Ожидает'), ('PAYED_PARTLY', 'Частично оплачен'), ('PAYED_FULLY', 'Полностью оплачен'), ('CANCELLED', 'Отменен')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentin',
            name='state',
            field=models.CharField(choices=[('NEW', 'Новый'), ('WAITING', 'Ожидает оплаты'), ('PROCESSED', 'Получен'), ('CANCELLED', 'Отменен')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'Активен'), ('ARCHIVED', 'Архивирован')], default='DRAFT', max_length=8),
        ),
    ]
