# Generated by Django 3.1.1 on 2020-09-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200927_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='state',
            field=models.CharField(blank=True, choices=[('NEW', 'Новый'), ('WAITING', 'Ожидает'), ('COMPLETED', 'Выполнен'), ('PROCESSING', 'Исполняется'), ('CANCELLED', 'Отменён')], max_length=20, null=True),
        ),
    ]
