# Generated by Django 2.2.16 on 2020-09-30 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_courseproduct_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseproduct',
            old_name='items',
            new_name='courses',
        ),
    ]
