# Generated by Django 3.1.1 on 2020-09-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200927_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseproduct',
            name='on_invoice_payed',
        ),
        migrations.RemoveField(
            model_name='courseproduct',
            name='on_order_new',
        ),
        migrations.AddField(
            model_name='clientorder',
            name='fulfill_on',
            field=models.CharField(blank=True, choices=[('CREATED', 'Заказ создан'), ('CONFIRMED', 'Заказ подтвердён'), ('ORDER_PAYED_FULL', 'Счет оплачен полностью'), ('ORDER_PAYED_PARTLY', 'Счет оплачен частично')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='state',
            field=models.CharField(blank=True, choices=[('NEW', 'Новый'), ('WAITING', 'Ожидает'), ('CONFIRMED', 'Подтверждён'), ('COMPLETED', 'Выполнен'), ('PROCESSING', 'Исполняется'), ('CANCELLED', 'Отменён')], max_length=20, null=True),
        ),
    ]
