# Generated by Django 3.1.1 on 2020-09-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200926_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentin',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('waiting', 'Waiting'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
