# Generated by Django 2.2.16 on 2020-10-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20201012_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseproduct',
            name='duration',
            field=models.DurationField(blank=True, help_text='Продолжительность обучения. Формат: DDD HH:MM:SS', null=True),
        ),
    ]
