# Generated by Django 3.1.1 on 2020-09-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_paymentin_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.product'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('waiting', 'Waiting'), ('payed_partly', 'Payed Partly'), ('payed_fully', 'Payed Fully'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
