# Generated by Django 3.0.2 on 2020-01-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20200109_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseproduct',
            old_name='number_of_video_meterials',
            new_name='number_of_video_materials',
        ),
    ]
