# Generated by Django 3.1.1 on 2020-09-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20200926_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentin',
            name='gateway',
        ),
        migrations.AddField(
            model_name='paymentin',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='Payment gateway', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
    ]
