# Generated by Django 3.0.2 on 2020-01-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20200109_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='code', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
