# Generated by Django 3.0.2 on 2020-01-09 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20200108_0027'),
        ('crm', '0007_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('new', 'New'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Имя Фамилия', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, help_text='Комментарии', null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Person')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Product')),
            ],
        ),
    ]
