# Generated by Django 2.2.16 on 2020-10-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0001_initial'),
        ('crm', '0002_courseproduct_course'),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProductPageExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_extension', to='crm.CourseProduct')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='siteroot.CourseProductPageExtension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManyCourseProductPageExtensionCMSPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='siteroot_manycourseproductpageextensioncmspluginconfig', serialize=False, to='cms.CMSPlugin')),
                ('course_page_extensions', models.ManyToManyField(blank=True, to='siteroot.CourseProductPageExtension')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CourseProductPageExtensionCMSPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='siteroot_courseproductpageextensioncmspluginconfig', serialize=False, to='cms.CMSPlugin')),
                ('course_page_extension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteroot.CourseProductPageExtension')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CourseProductCMSPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='siteroot_courseproductcmspluginconfig', serialize=False, to='cms.CMSPlugin')),
                ('success_message', models.TextField(blank=True, default='')),
                ('course_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.CourseProduct')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CourseCMSPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='siteroot_coursecmspluginconfig', serialize=False, to='cms.CMSPlugin')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.Course')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
