# Generated by Django 2.2.16 on 2020-10-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteroot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseproductcmspluginconfig',
            name='success_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
