# Generated by Django 2.2.16 on 2020-10-03 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('crm', '0003_auto_20201001_0228'),
        ('siteroot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProductCMSPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='siteroot_courseproductcmspluginconfig', serialize=False, to='cms.CMSPlugin')),
                ('course_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.CourseProduct')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CourseProductPageExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_extension', to='crm.CourseProduct')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='siteroot.CourseProductPageExtension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CourseCardCMSPluginConfig',
        ),
    ]
