# Generated by Django 2.2.16 on 2020-10-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20201003_1735'),
        ('cms', '0022_auto_20180620_1551'),
        ('siteroot', '0002_auto_20201003_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCMSPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='siteroot_coursecmspluginconfig', serialize=False, to='cms.CMSPlugin')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.Course')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
