# Generated by Django 2.2.16 on 2020-10-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteroot', '0004_manycourseproductscmspluginconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseproductcmspluginconfig',
            name='course_product',
        ),
        migrations.RemoveField(
            model_name='courseproductcmspluginconfig',
            name='page',
        ),
        migrations.AddField(
            model_name='courseproductcmspluginconfig',
            name='course_page_extension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteroot.CourseProductPageExtension'),
        ),
    ]
