# Generated by Django 2.2.16 on 2020-10-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('crm', '0003_auto_20201001_0228'),
        ('siteroot', '0005_auto_20201003_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseproductcmspluginconfig',
            name='course_page_extension',
        ),
        migrations.AddField(
            model_name='courseproductcmspluginconfig',
            name='course_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.CourseProduct'),
        ),
        migrations.CreateModel(
            name='CourseProductPageExtensionCMSPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='siteroot_courseproductpageextensioncmspluginconfig', serialize=False, to='cms.CMSPlugin')),
                ('course_page_extension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteroot.CourseProductPageExtension')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
