# Generated by Django 2.2.16 on 2020-10-03 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteroot', '0007_auto_20201003_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseproductcmspluginconfig',
            name='course_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.CourseProduct'),
        ),
        migrations.AlterField(
            model_name='courseproductpageextensioncmspluginconfig',
            name='course_page_extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteroot.CourseProductPageExtension'),
        ),
    ]
