# Generated by Django 2.2.16 on 2020-10-04 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteroot', '0010_auto_20201003_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseproductpageextensioncmspluginconfig',
            name='course_page_extension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteroot.CourseProductPageExtension'),
        ),
    ]
