# Generated by Django 2.2.16 on 2020-10-04 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteroot', '0011_auto_20201004_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseproductcmspluginconfig',
            name='course_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.CourseProduct'),
        ),
        migrations.AlterField(
            model_name='courseproductpageextension',
            name='course_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_extension', to='crm.CourseProduct'),
        ),
        migrations.AlterField(
            model_name='courseproductpageextensioncmspluginconfig',
            name='course_page_extension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteroot.CourseProductPageExtension'),
        ),
    ]
