# Generated by Django 2.2.16 on 2020-10-08 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.SlugField(default=uuid.uuid4, max_length=200, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='code',
            field=models.SlugField(default=uuid.uuid4, max_length=200, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.SlugField(default=uuid.uuid4, max_length=200, unique=True, verbose_name='Code'),
        ),
    ]
