# Generated by Django 2.2.16 on 2020-10-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproduct',
            name='license_duration',
            field=models.DurationField(blank=True, help_text='Срок выдачи лицензии. Если пусто, то бессрочная. Формат: DDD HH:MM:SS', null=True),
        ),
    ]
