# Generated by Django 2.2.16 on 2020-10-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='fulfill_on',
            field=models.CharField(blank=True, choices=[('CREATED', 'когда заказ создан'), ('CONFIRMED', 'когда заказ подтверждён'), ('ORDER_PAYED_FULL', 'когда счет оплачен полностью'), ('ORDER_PAYED_PARTLY', 'когда счет оплачен частично')], max_length=200, null=True),
        ),
    ]
