# Generated by Django 2.2.16 on 2020-10-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20201009_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=14),
        ),
    ]
