# Generated by Django 2.2.16 on 2020-10-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_digitalproduct_license_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='#'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='#'),
        ),
    ]
