# Generated by Django 2.2.16 on 2020-10-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20201011_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
